classDiagram
    class IPostalCode {
      +value: String
    }
    class IPostalCodeStrategy {
      +normalize(pc: IPostalCode): IPostalCode
      +validate(pc: IPostalCode): Boolean
    }
    class PostalCodeBrazil {
      +value: String
    }
    class BrazilPostalCodeStrategy {
      +normalize(pc: IPostalCode): IPostalCode
      +validate(pc: IPostalCode): Boolean
    }
    class PostalCodeStrategyFactory {
      +for(country): IPostalCodeStrategy
    }

    IPostalCode <|.. PostalCodeBrazil
    IPostalCodeStrategy <|.. BrazilPostalCodeStrategy
    PostalCodeStrategyFactory --> IPostalCodeStrategy
    BrazilPostalCodeStrategy --> PostalCodeBrazil
